/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as interfaces from "./interfaces";
export * as mocks from "./mocks";
export { CorpusNameService__factory } from "./CorpusNameService__factory";
export { CorpusRegistry__factory } from "./CorpusRegistry__factory";
